[pytest]
markers =
    ui:  for tests related to UI
    api: for tests related to API
    smoke:for smoke tests
    e2e: for end to end tests
    network_intercept: for tests related to network intercept